// <auto-generated />
namespace AnyStats___5204_PassionProject_n01442097.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class doubleyValue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(doubleyValue));
        
        string IMigrationMetadata.Id
        {
            get { return "202102190107112_double yValue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
