// <auto-generated />
namespace AnyStats___5204_PassionProject_n01442097.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class stat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stat));
        
        string IMigrationMetadata.Id
        {
            get { return "202102151740138_stat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
